### ISSUE TITLE
Cannot consume scoped service 'Finbuckle.MultiTenant.IMultiTenantStore`1[Finbuckle.MultiTenant.MongoTenantInfo]' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.

### ISSUE THREAD

**Issue by ruslankiskinov** [JohnCampionJr/Finbuckle.MultiTenant.MongoFramework#27]
I cannot start any of your examples because of the following error:

Cannot consume scoped service 'Finbuckle.MultiTenant.IMultiTenantStore`1[Finbuckle.MultiTenant.MongoTenantInfo]' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.

the problem is connected to this row from the Program.cs:
//NOTE: this service will be called by the runtime when application is actually started
**services.AddSingleton<IHostedService, ApplicationStartedService>();**

**Comment by JohnCampionJr** [comment]
Thank you for reporting this; will fix it ASAP
